# Background and foreground colors
background = #11141e
foreground = #f2f1fa

# Standard colors
palette = 0=#11141e
palette = 1=#aba8d7
palette = 2=#7f86b8
palette = 3=#a19ece
palette = 4=#7575aa
palette = 5=#9895c7
palette = 6=#a9accb
palette = 7=#b2afe1

# Bright colors
palette = 8=#7a829a
palette = 9=#e7e6f5
palette = 10=#b9bdda
palette = 11=#dbdaee
palette = 12=#acaccf
palette = 13=#d1d0e8
palette = 14=#e2e3ee
palette = 15=#f2f1fa
