background            #11141e
foreground            #f2f1fa

# black
color0  #11141e
color8  #7a829a

# red
color1  #aba8d7
color9  #e7e6f5

# green
color2  #7f86b8
color10 #b9bdda

# yellow
color3  #a19ece
color11 #dbdaee

# blue
color4  #7575aa
color12 #acaccf

# magenta
color5  #9895c7
color13 #d1d0e8

#cyan
color6  #a9accb
color14 #e2e3ee

#white
color7  #b2afe1
color15 #f2f1fa


